In [42]:
import numpy as np

def discretize_servo_positions(tempo_inizio, tempo_fine, posizione_inizio, posizione_fine, deltaT):
    
 
    # Calcola il numero di intervalli discreti per il set corrente di parametri
    L = int(np.round((tempo_fine - tempo_inizio) / deltaT)) + 1
        
    # Genera array di tempi discreti per il set corrente di parametri
    #tempi_discreti = np.linspace(tempo_inizio, tempo_fine, L)
    tempi_discreti = (np.linspace(tempo_inizio, tempo_fine, L)).astype(np.int64)
    print(tempi_discreti)
    print("-------------")
    
    # Interpola le posizioni dei servomotori per il set corrente di parametri
    posizioni_discrete = (np.linspace(posizione_inizio[0], posizione_fine[0], L)).astype(np.int64)
    
    # Crea una matrice per memorizzare i valori discretizzati per il set corrente di parametri
    matrice_discretizzata = np.vstack((posizioni_discrete, tempi_discreti))
        
    # Interpola le posizioni dei servomotori per il set corrente di parametri
    for i in range(1, 6):
        nuove_posizioni = (np.linspace(posizione_inizio[i], posizione_fine[i], L)).astype(np.int64)
        
        # Crea una matrice per memorizzare i valori discretizzati per il set corrente di parametri
        matrice_discretizzata = np.vstack((nuove_posizioni,matrice_discretizzata))
        
        # Aggiunge la matrice corrente alla lista
        #matrici_discretizzate.append(matrice_discretizzata)
    
    return matrice_discretizzata.T

# Esempio di utilizzo
tempo_inizio = 0
tempo_fine = 121
posizione_inizio = [0, 0, 0, 0, 0, 0]
posizione_fine = [90, 100, 100, 100, 100, 100]
deltaT = 10

# Chiama la funzione
risultato = discretize_servo_positions(tempo_inizio, tempo_fine, posizione_inizio, posizione_fine, deltaT)

print(risultato)


[  0  10  20  30  40  50  60  70  80  90 100 110 121]
-------------
[[  0   0   0   0   0   0   0]
 [  8   8   8   8   8   7  10]
 [ 16  16  16  16  16  15  20]
 [ 25  25  25  25  25  22  30]
 [ 33  33  33  33  33  30  40]
 [ 41  41  41  41  41  37  50]
 [ 50  50  50  50  50  45  60]
 [ 58  58  58  58  58  52  70]
 [ 66  66  66  66  66  60  80]
 [ 75  75  75  75  75  67  90]
 [ 83  83  83  83  83  75 100]
 [ 91  91  91  91  91  82 110]
 [100 100 100 100 100  90 121]]
